//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Request.proto
namespace hrv
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private hrv.Request.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public hrv.Request.Type type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _timestamp = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=0)]
      LOGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_PASSWORD", Value=1)]
      CHANGE_PASSWORD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_SCALE", Value=2)]
      START_SCALE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP_SCALE", Value=3)]
      STOP_SCALE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_PPG", Value=4)]
      DATA_PPG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_EP", Value=5)]
      DATA_EP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_HRV", Value=6)]
      DATA_HRV = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_IBI", Value=7)]
      DATA_IBI = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MARK_SCALE", Value=8)]
      MARK_SCALE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_LIST", Value=9)]
      RESOURCE_LIST = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_USER_INFO", Value=10)]
      UPDATE_USER_INFO = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_SCALE_LIST", Value=11)]
      GET_SCALE_LIST = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_SCALE", Value=12)]
      GET_SCALE = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}