//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserInfo.proto
namespace hrv
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }

    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private string _birthday = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"birthday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string birthday
    {
      get { return _birthday; }
      set { _birthday = value; }
    }

    private string _mobile = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mobile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobile
    {
      get { return _mobile; }
      set { _mobile = value; }
    }

    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }

    private int _weight = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"weight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int weight
    {
      get { return _weight; }
      set { _weight = value; }
    }

    private string _workingPlace = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"workingPlace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string workingPlace
    {
      get { return _workingPlace; }
      set { _workingPlace = value; }
    }

    private string _position = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string position
    {
      get { return _position; }
      set { _position = value; }
    }

    private string _medicalHistory = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"medicalHistory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string medicalHistory
    {
      get { return _medicalHistory; }
      set { _medicalHistory = value; }
    }

    private bool _locked = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool locked
    {
      get { return _locked; }
      set { _locked = value; }
    }

    private string _realName = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"realName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string realName
    {
      get { return _realName; }
      set { _realName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}